<?php
return [
  'dinased' => [
    'DINASED AZUAY','DINASED BOLIVAR','DINASED CAÑAR','DINASED CARCHI','DINASED CHIMBORAZO',
    'DINASED COTOPAXI','DINASED DMG','DINASED DMQ','DINASED EL ORO','DINASED ESMERALDAS',
    'DINASED GALAPAGOS','DINASED GUAYAS','DINASED IMBABURA','DINASED LOJA','DINASED LOS RIOS',
    'DINASED MANABI','DINASED MORONA SANTIAGO','DINASED NAPO','DINASED ORELLANA','DINASED PASTAZA',
    'DINASED PICHINCHA','DINASED SANTA ELENA','DINASED SANTO DOMINGO','DINASED SUCUMBIOS',
    'DINASED TUNGURAHUA','DINASED ZAMORA CHINCHIPE',
  ],
];
