<?php
return [
    // Fiscalía (listas editables)
    'fiscalias_nombres' => [
		'UNIDAD NACIONAL PARA LA INVESTIGACIÓN PATRIMONIAL SOBRE EXTINCIÓN DE DOMINIO',
        'UNIDAD ESPECIALIZADA PARA LA INVESTIGACIÓN DE LOS DELITOS CONTRA EL MEDIO AMBIENTE Y LA NATURALEZA',
        'UNIDAD NACIONAL ESPECIALIZADA DE INVESTIGACIÓN CONTRA LA DELINCUENCIA ORGANIZADA TRANSNACIONAL – UNIDOT',
        'UNIDAD NACIONAL ESPECIALIZADA EN INVESTIGACIÓN DE CIBERDELITO',
        'DELINCUENCIA ORGANIZADA TRANSNACIONAL E INTERNACIONAL (FEDOTI)',
        'UNIDAD ESPECIALIZADA DE LA COMISIÓN DE LA VERDAD Y DERECHOS HUMANOS',
        'FISCALÍA DE INVESTIGACIÓN DE PERSONAS DESAPARECIDAS',
        'UNIDAD SELECTA CONTRA EL LAVADO DE ACTIVOS',
        'UNIDAD NACIONAL DE TRANSPARENCIA Y LUCHA CONTRA LA CORRUPCIÓN',
        'FISCALÍA ESPECIALIZADA EN SOLUCIONES RAPIDAS',
        'ADMINISTRACIÓN PÚBLICA',
        'PERSONAS Y GARANTÍAS',
        'JUSTICIA JUVENIL',
        'VIOLENCIA DE GÉNERO',
        'PATRIMONIO CIUDADANO',
        'FE PÚBLICA',
        'FISCALÍA ESPECIALIZADA EN INVESTIGACIÓN DE ACCIDENTES DE TRÁNSITO',
        'UNIDAD DE ACTUACIONES ADMINISTRATIVAS',
        'FISCALÍA ESPECIALIZADA EN ADMINISTRACION PUBLICA',
        'FISCALÍA ESPECIALIZADA EN SOLUCIONES RAPIDAS',
        'FISCALÍA ESPECIALIZADA EN VIOLENCIA DE GENERO',
        'FISCALÍA ESPECIALIZADA EN PATRIMONIO CIUDADANO',
        'FISCALÍA ESPECIALIZADA EN FE PUBLICA',
        'FISCALÍA ESPECIALIZADA EN DELITOS ACUÁTICOS',
        'FISCALÍA ESPECIALIZADA EN ADOLESCENTES INFRACTORES',
        'UNIDAD DE DESCUBRIR AUTORES, COMPLICES Y ENCUBRIDORES',
        'FISCALÍA ESPECIALIZADA EN PERSONAS Y GARANTIAS',
        'FISCALÍA ESPECIALIZADA EN VIOLENCIA CONTRA LA MUJER Y MIEMBROS DEL NUCLEO FAMILIAR',
        'DIRECCIÓN DE DERECHOS HUMANOS Y PARTICIPACIÓN CIUDADANA',
        'ASUNTOS INDIGENAS',
        'UNIDAD ANTILAVADO DE ACTIVOS',
        'FISCALÍA ESPECIALIZADA EN ASUNTOS PENALES',
        'UNIDAD DE FLAGRANCIA',
        'SERVICIO DE ATENCIÓN INTEGRAL',
        'FISCALÍA DE FUERO PROVINCIAL',
        'UNIDAD DE FUERO DE CORTE NACIONAL',
        'FISCALÍA PROVINCIAL DE INVESTIGACION DE ORIENTE',
        'UNIDAD DE GESTION DE SERVICIOS REGIONALES',
        'FISCALÍA MULTICOMPETENTE',
        'FISCALÍA ESPECIALIZADA EN JUSTICIA JUVENIL',
        'UNIDAD DE INVESTIGACION SELECTA ESPECIALIZADA EN TRANSPARENCIA',
        'UNIDAD DE SISTEMA DE CONTROL DE MEDIOS',
        'UNIDAD NACIONAL DE INVESTIGACION DE CASOS DE ALTA COMPLEJIDAD',
        'FISCALÍA ESPECIALIZADA EN ATENCIÓN A PERSONAS MIGRANTES',
        'FISCALÍAS CANTONALES',
        'FISCALÍAS PROVINCIALES','OTRO',
    ],
    
	
	
	    'fiscalias_numeros' => array_merge(
        array_map(fn($n) => str_pad($n, 2, '0', STR_PAD_LEFT), range(1, 50)),
        ['OTRO']
    ),
	
	
	
    // Fiscales delegados (muestra algunos + OTRO)
    'fiscales_delegados' => [
'ABG. ACOSTA CASTRO ROBERT DAVID',
        'ABG. ACURIO QUEZADA KATIA ALEXANDRA',
        'ABG. ALMEIDA DELGADO GIANCARLO LADISLAO',
        'ABG. ALMEIDA VILLEGAS MARTIN FERNANDO',
        'ABG. ALTAMIRANO CARTAGENA VICTOR ELICEO',
        'ABG. ALVAREZ VALENCIA WILSON ENRIQUE',
        'ABG. ANDRADE MATUTE JACINTA MARIA',
        'ABG. ANDRADE RIVERA JOSE LUIS',
        'ABG. ARECHUA CAZA SEGUNDO RUBEN',
        'ABG. ARGUDO BARROSO ORLY EDGAR',
        'ABG. ARMIJOS MORAN GIOCONDA AUXILIADORA',
        'ABG. ARTEAGA LINDAO YARILDA TAHYNA',
        'ABG. BALDEON HERRERA DARWIN OSWALDO',
        'ABG. BAQUERIZO BALLADARES NARCISA MIXILI',
        'ABG. BARCO LOOR INES MARIA',
        'ABG. BARRAGAN ALVAREZ LISSET GLORIA',
        'ABG. BAZURTO QUINDE ENRY JIMEN',
        'ABG. BODERO CARRION FRANCISCO JAVIER',
        'ABG. BOLAÑOS MORENO JENNIFER GRACE',
        'ABG. BONI ALAY WELLINGTON ROBERTO',
        'ABG. BONOSO LEON CARLOS FERNANDO',
        'ABG. BRAVO SALAZAR JOSE OSWALDO',
        'ABG. BRIONES VALERO EDMUNDO ALBERTO',
        'ABG. CACERES JIMENEZ PABLO HUMBERTO',
        'ABG. CAICEDO VALENCIA YEFERSON CRISTIAN',
        'ABG. CAICHE MEJILLON JORGE EDUARDO',
        'ABG. CALDERON NAVARRETE VICTOR HUGO',
        'ABG. CALIXTO ALAVA FELICIANA AIDA',
        'ABG. CALVOPIÑA LLAMBO ANA VERONICA',
        'ABG. CAMATON BORBOR DOMINGA AZUCENA',
        'ABG. CAMPOS QUINTANA FRANCISCO GUSTAVO',
        'ABG. CARANQUI MOROCHO CARLOS ARMANDO',
        'ABG. CARDENAS RUIZ WALTER OSWALDO',
        'ABG. CARDENAS VERDEZOTO JORGE WASHINGTON',
        'ABG. CASTAÑEDA PENA EDWIN ROLANDO',
        'ABG. CASTRO BALLADARES BYRON VINICIO',
        'ABG. CASTRO CORONEL BEPSABETH ALEXANDRA',
        'ABG. CASTRO SANCHEZ FANNY CARLOTA',
        'ABG. CENTENO GUERRERO LUIS WILSON',
        'ABG. CEVALLOS FREIRE REINALDO EFRAIN',
        'ABG. CEVALLOS ZHUNAULA FRANCO ANTONIO',
        'ABG. CHACHO YEPEZ CELINDA KARINA',
        'ABG. CHACON CHACON LAURA ESTELA',
        'ABG. CHANGO LLERENA DIEGO VINICIO',
        'ABG. CHONILLO MUÑOZ ALFREDO LEANDRO',
        'ABG. CHUQUI RIVADENEIRA LESLIE SILVANA',
        'ABG. COCA TORRES STALIN ELY',
        'ABG. CONCHA ESTEBAN MARIA ALEJANDRA',
        'ABG. CONFORME ZAMBRANO SOBEIDA ARACELY',
        'ABG. CORONEL LUCERO ROBINSON RENE',
        'ABG. DAQUILEMA QUISHPI EDISON PATRICIO',
        'ABG. DELGADO INTRIAGO LILIANA CECIBEL',
        'ABG. DELGADO MONTANERO CARLOS JAVIER',
        'ABG. DIAZ ZAMBRANO EDUARDO ANTONIO',
        'ABG. DUEÑAS PORRAS NEIL EDWARD',
        'ABG. ELIZALDE TORRES ERROL ENRIQUE',
        'ABG. ESCALA JORDAN YELA MARIUXY',
        'ABG. ESCOBAR ARRIETA MARCO VINICIO',
        'ABG. ESCOBAR LIMONES MARJORIE JANET',
        'ABG. ESPINOZA ESTEVES XAVIER NOE PATRICIO',
        'ABG. FAREZ FALCONI CHRISTIAN HUMBERTO',
        'ABG. FIGUEROA DUTASACA MARIBEL DOLORES',
        'ABG. FLORES CATUTO FRANKLIN GEOVANNY',
        'ABG. FRANCO LOPEZ CARLOS ROBERTO',
        'ABG. FREIRE BAJAÑA MODESTO ARIOSTO',
        'ABG. GAIBOR MUÑOZ MARCO ALEXANDER',
        'ABG. GALARZA GOMEZ MIRIAN ALEXANDRA',
        'ABG. GALLEGOS MOREJON ROSALINA MONSERRAT',
        'ABG. GALVEZ MORALES MARIA LIVANEZA',
        'ABG. GARCIA VARGAS HUGO NAPOLEON',
        'ABG. GONZALEZ DELGADO VICTOR HUGO',
        'ABG. GONZALEZ GAME EMILI ELIZABETH',
        'ABG. GONZALEZ MORA JOFFRE ALCIBIADES',
        'ABG. GRANJA CHIRIBOGA MIGUEL ANGEL',
        'ABG. GUALOTO BURGOS TANIA MARIA',
        'ABG. GUAMAN SAGÑAY JUAN BOLIVAR',
        'ABG. GUERRON REINOSO CARLOS ROBERTO',
        'ABG. GUEVARA PAREDES MARIA PIEDAD',
        'ABG. GUZMAN FRANCO JOHNNY BENJAMIN',
        'ABG. GUZMAN ZAMBRANO FRESIA REGINA',
        'ABG. HARO HARO MARIBEL NATALI',
        'ABG. HIDALGO VEGA WILFRIDO RUPERTO',
        'ABG. HOLGUIN RUIZ NOEMI MIREYA',
        'ABG. INGA BRIONES ISABEL MARGARITA',
        'ABG. INTRIAGO LEONES PEDRO GEOVANY',
        'ABG. INTRIAGO MARTINEZ WILMER JEAN CARLOS',
        'ABG. ITURRALDE HIDALGO JUAN CARLOS',
        'ABG. JACOME ARISTEGA PETER NILCON',
        'ABG. JARA RUBIO SAIRA DE LOS ANGELES',
        'ABG. JARAMILLO LINO WALTHER ABEL',
        'ABG. KINCHUELA MORAN KAREN LUISA',
        'ABG. LEON TENORIO VICTOR HUGO',
        'ABG. LOMAS FRANCO BELINDA ANNETTE',
        'ABG. LOPEZ AVILA ALEX JAVIER',
        'ABG. LOPEZ CEREZO GREGORIO MALAQUIAS',
        'ABG. LUCAS CENTENO SEGUNDO AMBROSIO',
        'ABG. LUNA QUINDE MICHELL ERIKA',
        'ABG. MACIAS MIRANDA NELSON ELIO',
        'ABG. MARIN PAREDES ALICIA DE LAS MERCEDES',
        'ABG. MATAMOROS CHACA ROSA CATALINA',
        'ABG. MEDINA PINCAY LAURA DEL ROCIO',
        'ABG. MENDOZA PIGUAVE FRANZ ENRIQUE',
        'ABG. MOGROVEJO MORALES MANUEL ALEJANDRO',
        'ABG. MONCAYO BONILLA MIRIAN ROSARIO',
        'ABG. MORA QUEVEDO DANNY ALBERTO',
        'ABG. MORALES ANCHUNDIA JOSE VICENTE',
        'ABG. MORALES FARIAS WALTER ALFREDO',
        'ABG. MORAN ARREAGA NINA EVELYN',
        'ABG. MORAN ESPINOZA MARY PATRICIA',
        'ABG. MUÑOZ MORA DARWIN DAVID',
        'ABG. NARANJO PINCAY STALIN JAVIER',
        'ABG. NEIRA JIMENEZ FABRIZZIO JOSE',
        'ABG. NEIRA MORAN RUTH MARGARITA',
        'ABG. NEIRA REINOSO MIRIAM ELIZABETH',
        'ABG. NELSON DEL CASTILLO MANUEL DAVID',
        'ABG. NOBLECILLA GUERRERO BLANCA PIEDAD',
        'ABG. PALIZ VISCARRA JENNY PRISSILA',
        'ABG. PARADA VELOZ LOURDES VERONICA',
        'ABG. PAREDES VILELA NELSON EDUARDO',
        'ABG. PATIÑO MOREIRA MILTON ARNOLDO',
        'ABG. PAZ Y MIÑO MONCAYO LUZ ISABEL',
        'ABG. PEÑA MENA LUIS EDUARDO',
        'ABG. PEÑA MERINO CECILIA ELIZABETH',
        'ABG. PEÑA MORAN CESAR ARMANDO',
        'ABG. PEREZ ORTEGA RUBEN LEONELO',
        'ABG. PICO JIJON PAOLA KATHERINE',
        'ABG. PIEDRA GARAICOA CARLOS RAPHAEL',
        'ABG. PINCAY DELGADO WILLIAMS IVAN',
        'ABG. PINEDA MAZA WILLIAM PATRICIO',
        'ABG. PITA PAZMIÑO IRMA MERCEDES',
        'ABG. POSLIGUA VALENZUELA LISSETTE JAZMIN',
        'ABG. PUCHA PAGUAY JAVIER GEOVANNY',
        'ABG. PUGA TORRES IVONNE MARJORIE',
        'ABG. PULECIO MONTALVO NICOLAS ERNESTO',
        'ABG. QUISHPE CAIZA PAULO CESAR',
        'ABG. RAMOS ECHEVERRIA MIGUEL ANGEL',
        'ABG. RIVADENEIRA MACIAS HIPOLITO SANTIAGO',
        'ABG. RODRIGUEZ ARBOLEDA NORMA CECILIA',
        'ABG. ROLDAN CRUZ DIANA MARIA',
        'ABG. ROMERO CASTRO ALVARO MAURICIO',
        'ABG. ROMERO JAEN WALTER JUNIOR',
        'ABG. RUIZ BRIONES BLANCA CAROLINA',
        'ABG. RUIZ LOPEZ RODRIGO OSWALDO',
        'ABG. RUIZ MONCAYO ANABEL ELIZABETH',
        'ABG. RUIZ MORAN JUAN EMILIO',
        'ABG. SALTOS HAON FRANKLIN ARMANDO',
        'ABG. SANCHEZ MERA JULIO AGUBERTO',
        'ABG. SANCHEZ VELEZ JOSE ALBERTO',
        'ABG. SANTANA NAVARRO NARCISA CONSUELO',
        'ABG. SANTILLAN NAVARRO MARCOS DANNY',
        'ABG. SEGARRA MORAN SARITA DELIA',
        'ABG. SEVILLA JARA ROMULO',
        'ABG. SIGCHO JUNCO GLORIA MARIA',
        'ABG. SOLEDISPA CAMPOS MERCY CRISTINA',
        'ABG. SUAREZ SALTOS WASHINGTON FRANCISCO',
        'ABG. SUPLEWICH NARVAEZ MAO EMMANUEL',
        'ABG. TOALA CAÑARTE FREDDY HERIBERTO',
        'ABG. TOLEDO LLERENA LUIS PATRICIO',
        'ABG. TORRES RONQUILLO FRANKLIN AURELIO',
        'ABG. TRUJILLO GARCIA CESAR HOLGER',
        'ABG. TUTIVEN GALVEZ JUDY VANESSA',
        'ABG. URIGUEN URIGUEN MICHAEL JOHNROSS',
        'ABG. VACA GRIJALVA CARLOS ENRIQUE',
        'ABG. VALVERDE SOLIS HECTOR ANTONIO',
        'ABG. VARGAS ORTIZ MARCO ANTONIO',
        'ABG. VASQUEZ LOPEZ GIOVANNA KATIUSKA',
        'ABG. VELA ANDRADE NELSON DANIEL',
        'ABG. VELASCO SOLIS JOFFRE ALFREDO',
        'ABG. VELEZ FUENTES OLMEDO',
        'ABG. VELEZ LEON MIGUEL MARCELO',
        'ABG. VERA ARIAS ZOILA PRICILA',
        'ABG. VILLAGOMEZ OÑATE MARIA YANINA',
        'ABG. VILLALTA GAVILANES LUIS ANTONIO',
        'ABG. VILLARREAL CARDENAS TONSHAY JOSEFINA',
        'ABG. VIZUETA PRADO DANNY ROY',
        'ABG. YAVAR NUÑEZ FERNANDO JOSE',
        'ABG. ZAMBRANO BERMUDEZ GEOVANNI EDILBERTO',
        'ABG. ZAMBRANO SOLORZANO FABRICIO FERNANDO',
        'ABG. ZAPATA ESPAÑA DANIELA MARISOL',
        'ABG. ZUÑIGA MUÑOZ ALEXIS FERNANDO',
        'ABG. ZURITA MURILLO AMELIA CARLOTA',
        'OTRO',
    ],

    // Tipo penal (formulación)
    'tipos_penales' => [
	    'Art. 39 Tentativa',
       'Art. 79 Genocidio',
        'Art. 80 Etnocidio',
        'Art. 81 Exterminio',
        'Art. 82 Esclavitud',
        'Art. 83 Deportación o traslado forzoso de población',
        'Art. 84 Desaparición forzada',
        'Art. 85 Ejecución extrajudicial',
        'Art. 86 Persecución',
        'Art. 87 Apartheid',
        'Art. 89 Delitos de lesa humanidad',
        'Art. 91 Trata de personas',
        'Art. 96 Tráfico de órganos',
        'Art. 97 Publicidad de tráfico de órganos',
        'Art. 98 Realización de procedimientos de trasplante sin autorización',
        'Art. 99 Turismo para la extracción, tratamiento ilegal o comercio de órganos',
        'Art. 100 Explotación sexual de personas',
        'Art. 101 Prostitución forzada',
        'Art. 102 Turismo sexual',
        'Art. 103 Pornografía con utilización de niñas, niños o adolescentes',
        'Art. 104 Comercialización de pornografía con utilización de niñas, niños o adolescentes',
        'Art. 105 Trabajos forzados u otras formas de explotación laboral',
        'Art. 106 Promesa de matrimonio o unión de hecho servil',
        'Art. 107 Adopción ilegal',
        'Art. 108 Empleo de personas para mendicidad',
        'Art. 115 Homicidio de persona protegida',
        'Art. 118 Mutilaciones o experimentos en persona protegida',
        'Art. 119 Tortura y tratos crueles, inhumanos o degradantes en persona protegida',
        'Art. 120 Castigos colectivos en persona protegida',
        'Art. 121 Empleo de métodos prohibidos en la conducción de conflicto armado',
        'Art. 122 Utilización de armas prohibidas',
        'Art. 123 Ataque a bienes protegidos',
        'Art. 124 Obstaculización de tareas sanitarias y humanitarias',
        'Art. 125 Privación de libertad de persona protegida',
        'Art. 126 Ataque a persona protegida con fines terroristas',
        'Art. 127 Reclutamiento de niños, niñas y adolescentes',
        'Art. 128 Toma de rehenes',
        'Art. 129 Infracciones contra los prisioneros de guerra, personas que ya no participan en las hostilidades u otra persona protegida',
        'Art. 130 Traslado arbitrario o ilegal',
        'Art. 131 Abolición y suspensión de derechos de persona protegida',
        'Art. 132 Modificación ambiental con fines militares',
        'Art. 133 Denegación de garantías judiciales de persona protegida',
        'Art. 134 Omisión de medidas de socorro y asistencia humanitaria',
        'Art. 135 Omisión de medidas de protección',
        'Art. 136 Contribuciones arbitrarias',
        'Art. 137 Prolongación de hostilidades',
        'Art. 138 Destrucción o apropiación de bienes de la parte adversa',
        'Art. 139 Abuso de emblemas',
        'Art. 140 Asesinato',
        'Art. 141 Femicidio',
        'Art. 143 Sicariato',
        'Art. 144 Homicidio',
        'Art. 145 Homicidio culposo',
        'Art. 146 Homicidio culposo por mala práctica profesional',
        'Art. 147 Aborto con muerte',
        'Art. 148 Aborto no consentido',
        'Art. 151 Tortura',
        'Art. 152 Lesiones',
        'Art. 153 Abandono de persona',
        'Art. 154 Intimidación',
        'Art. 154,1 Instigación al suicidio',
        'Art. 154,2 Hostigamiento',
        'Art. 156 Violencia física contra la mujer o miembros del núcleo familiar',
        'Art. 157 Violencia psicológica contra la mujer o miembros del núcleo familiar',
        'Art. 158 Violencia sexual contra la mujer o miembros del núcleo familiar',
        'Art. 160 Privación ilegal de libertad',
        'Art. 161 Secuestro',
        'Art. 162 Secuestro extorsivo',
        'Art. 163 Simulación de secuestro',
        'Art. 163,1 Desaparición involuntaria',
        'Art. 164 Inseminación no consentida',
        'Art. 165 Privación forzada de capacidad de reproducción',
        'Art. 166 Acoso sexual',
        'Art. 167 Estupro',
        'Art. 168 Distribución de material pornográfico a niñas, niños y adolescentes',
        'Art. 169 Corrupción de niñas, niños y adolescentes',
        'Art. 170 Abuso sexual',
        'Art. 171 Violación',
        'Art. 171,1 Violación incestuosa',
        'Art. 172 Utilización de personas para exhibición pública con fines de naturaleza sexual',
        'Art. 173 Contacto con finalidad sexual con menores de 18 años por medios electrónicos',
        'Art. 174 Oferta de servicios sexuales con menores de 18 años por medios electrónicos',
        'Art. 176 Discriminación',
        'Art. 177 Actos de odio',
        'Art. 178 Violación a la intimidad',
        'Art. 179 Revelación de secreto o información personal de terceros',
        'Art. 180 Difusión de información de circulación restringida',
        'Art. 181 Violación de propiedad privada',
        'Art. 182 Calumnia',
        'Art. 183 Restricción a la libertad de expresión',
        'Art. 184 Restricción a la libertad de culto',
        'Art. 185 Extorsión',
        'Art. 186 Estafa',
        'Art. 187 Abuso de confianza',
        'Art. 188 Aprovechamiento ilícito de servicios públicos',
        'Art. 189 Robo',
        'Art. 190 Apropiación fraudulenta por medios electrónicos',
        'Art. 191 Reprogramación o modificación de información de equipos terminales móviles',
        'Art. 192 Intercambio, comercialización o compra de información de equipos terminales móviles',
        'Art. 193 Reemplazo de identificación de terminales móviles',
        'Art. 194 Comercialización ilícita de terminales móviles',
        'Art. 195 Infraestructura ilícita',
        'Art. 196 Hurto',
        'Art. 197 Hurto de bienes de uso policial o militar',
        'Art. 199 Abigeato',
        'Art. 200 Usurpación',
        'Art. 201 Ocupación, uso ilegal de suelo o tráfico de tierras',
        'Art. 202 Receptación',
        'Art. 203 Comercialización de bienes de uso policial o militar hurtados o robados',
        'Art. 205 Insolvencia fraudulenta',
        'Art. 206 Quiebra',
        'Art. 207 Quiebra fraudulenta de persona jurídica',
        'Art. 208 Ocultamiento y otros actos fraudulentos en beneficio del fallido',
        'Art. 208A Actos lesivos a la propiedad intelectual',
        'Art. 208B Actos lesivos a los derechos de autor',
        'Art. 211 Supresión, alteración o suposición de la identidad y estado civil',
        'Art. 212 Suplantación de identidad',
        'Art. 213 Tráfico ilícito de migrantes',
        'Art. 214 Manipulación genética',
        'Art. 215 Daño permanente a la salud',
        'Art. 216 Contaminación de sustancias destinadas al consumo humano',
        'Art. 218 Desatención del servicio de salud',
        'Art. 219 Producción ilícita de sustancias catalogadas sujetas a fiscalización',
        'Art. 220 Tráfico ilícito de sustancias catalogadas sujetas a fiscalización',
        'Art. 221 Organización o financiamiento para la producción o tráfico ilícitos de sustancias catalogadas sujetas a fiscalización',
        'Art. 222 Siembra o cultivo',
        'Art. 224 Prescripción injustificada',
        'Art. 225 Acciones de mala fe para involucrar en delitos',
        'Art. 229 Revelación ilegal de base de datos',
        'Art. 230 Interceptación ilegal de datos',
        'Art. 231 Transferencia electrónica de activo patrimonial',
        'Art. 232 Ataque a la integridad de sistemas informáticos',
        'Art. 233 Delitos contra la información pública reservada legalmente',
        'Art. 234 Acceso no consentido a un sistema informático, telemático o de telecomunicaciones',
        'Art. 234.1 Falsificación informática',
        'Art. 235 Engaño al comprador respecto a la identidad o calidad de las cosas o servicios vendidos',
        'Art. 236 Casinos/salas de juego/casas de apuestas/negocios dedicados a juegos de azar',
        'Art. 237 Destrucción de bienes del patrimonio cultural',
        'Art. 238 Transporte y comercialización ilícitos y tráfico de bienes del patrimonio cultural',
        'Art. 239 Falsificación o adulteración de bienes del patrimonio cultural',
        'Art. 240 Sustracción de bienes del patrimonio cultural',
        'Art. 241 Impedimento o limitación del derecho a huelga',
        'Art. 242 Retención ilegal de aportación a la seguridad social',
        'Art. 244 Falta de afiliación al IESS',
        'Art. 245 Invasión de áreas de importancia ecológica',
        'Art. 246 Incendios forestales y de vegetación',
        'Art. 247 Delitos contra la flora y fauna silvestres',
        'Art. 248 Delitos contra los recursos del patrimonio genético nacional',
        'Art. 249 Lesiones a animales de la fauna urbana',
        'Art. 250 Abuso sexual a animales de la fauna urbana',
        'Art. 250.1 Muerte a animal de la fauna urbana',
        'Art. 250.2 Peleas o combates entre perros u otros animales de fauna urbana',
        'Art. 251 Delitos contra el agua',
        'Art. 252 Delitos contra suelo',
        'Art. 253 Contaminación del aire',
        'Art. 254 Gestión prohibida o no autorizada de productos, residuos, desechos o sustancias peligrosas',
        'Art. 255 Falsedad u ocultamiento de información ambiental',
        'Art. 260 Actividad ilícita de recursos mineros',
        'Art. 261 Financiamiento o suministro de maquinarias para extracción ilícita de recursos mineros',
        'Art. 262 Paralización del servicio de distribución de combustibles',
        'Art. 263 Adulteración de la calidad o cantidad de productos derivados de hidrocarburos, GLP o biocombustibles',
        'Art. 264 Almacenamiento/transporte/envasado/comercialización/distribución ilegal de productos derivados de hidrocarburos, GLP o biocombustibles',
        'Art. 266 Sustracción de hidrocarburos',
        'Art. 268 Prevaricato de jueces o árbitros',
        'Art. 269 Prevaricato de abogados',
        'Art. 270 Perjurio y falso testimonio',
        'Art. 270.1 Obstrucción de la justicia',
        'Art. 271 Acusación o denuncia maliciosa',
        'Art. 272 Fraude procesal',
        'Art. 273 Revelación de identidad de agente encubierto/informante/testigo/persona o funcionario judicial protegido',
        'Art. 274 Evasión o fuga',
        'Art. 275 Ingreso de artículos prohibidos',
        'Art. 276 Omisión de denuncia por razón de la profesión, cargo u oficio',
        'Art. 278 Peculado',
        'Art. 279 Enriquecimiento ilícito',
        'Art. 280 Cohecho',
        'Art. 281 Concusión',
        'Art. 282 Incumplimiento de decisiones legítimas de autoridad competente',
        'Art. 283 Ataque o resistencia',
        'Art. 284 Ruptura de sellos',
        'Art. 285 Tráfico de influencias',
        'Art. 286 Oferta de realizar tráfico de influencias',
        'Art. 287 Usurpación y simulación de funciones públicas',
        'Art. 288 Uso de fuerza pública contra órdenes de autoridad',
        'Art. 289 Testaferrismo',
        'Art. 290 Delitos contra bienes institucionales de FF.AA., Policía o SNAI/AI',
        'Art. 291 Elusión de responsabilidades de FF.AA. o Policía',
        'Art. 292 Alteración de evidencias y elementos de prueba',
        'Art. 293 Extralimitación en la ejecución de un acto de servicio',
        'Art. 294 Abuso de facultades',
        'Art. 294.1 Sobreprecios en contratación pública',
        'Art. 297 Enriquecimiento privado no justificado',
        'Art. 298 Defraudación tributaria',
        'Art. 299 Defraudación aduanera',
        'Art. 301 Contrabando',
        'Art. 302 Mal uso de exenciones o suspensiones tributarias aduaneras',
        'Art. 304 Tráfico de moneda',
        'Art. 305 Producción, tenencia y tráfico de instrumentos destinados a la falsificación de moneda',
        'Art. 306 Falsificación de moneda y otros documentos',
        'Art. 307 Pánico económico',
        'Art. 308 Agiotaje',
        'Art. 309 Usura',
        'Art. 310 Divulgación de información financiera reservada',
        'Art. 311 Ocultamiento de información',
        'Art. 312 Falsedad de información',
        'Art. 313 Defraudaciones bursátiles',
        'Art. 314 Falsedad documental en el mercado de valores',
        'Art. 315 Autorización indebida de contrato de seguro',
        'Art. 316 Operaciones indebidas de seguros',
        'Art. 317 Lavado de activos',
        'Art. 318 Incriminación falsa por lavado de activos',
        'Art. 319 Omisión de control de lavado de activos',
        'Art. 320 Simulación de exportaciones o importaciones',
        'Art. 320.1 Actos de corrupción en el sector privado',
        'Art. 322 Pánico financiero',
        'Art. 323 Captación ilegal de dinero',
        'Art. 324 Falsedad de información financiera',
        'Art. 327 Falsificación de firmas',
        'Art. 328 Falsificación y uso de documento falso',
        'Art. 328.1 Falsedad de contenido en recetas, exámenes o certificados médicos',
        'Art. 329 Falsificación, forjamiento o alteración de recetas',
        'Art. 330 Ejercicio ilegal de la profesión',
        'Art. 331 Obstaculización de proceso electoral',
        'Art. 332 Sustracción de papeletas electorales',
        'Art. 333 Falso sufragio',
        'Art. 334 Fraude electoral',
        'Art. 336 Rebelión',
        'Art. 337 Destrucción o inutilización de bienes',
        'Art. 338 Usurpación y retención ilegal de mando',
        'Art. 339 Actos hostiles contra el Estado',
        'Art. 340 Quebrantamiento de tregua o armisticio',
        'Art. 341 Tentativa de asesinato contra el Presidente de la República',
        'Art. 342 Sedición',
        'Art. 343 Insubordinación',
        'Art. 344 Abstención de la ejecución de operaciones en conmoción interna',
        'Art. 345 Sabotaje',
        'Art. 346 Paralización de un servicio público',
        'Art. 347 Destrucción de registros',
        'Art. 348 Incitación a discordia entre ciudadanos',
        'Art. 349 Grupos subversivos',
        'Art. 350 Instrucción militar ilegal',
        'Art. 351 Infiltración en zonas de seguridad',
        'Art. 352 Ocultamiento de objetos para el socorro',
        'Art. 353 Traición a la Patria',
        'Art. 354 Espionaje',
        'Art. 355 Omisión en el abastecimiento',
        'Art. 356 Atentado contra la seguridad de las operaciones militares o policiales',
        'Art. 357 Deserción',
        'Art. 358 Omisión de aviso de deserción',
        'Art. 360 Tenencia y porte no autorizado de armas',
        'Art. 361 Armas de fuego, municiones y explosivos prohibidos o no autorizados',
        'Art. 362 Tráfico ilícito de armas de fuego, armas químicas, nucleares o biológicas',
        'Art. 363 Instigación',
        'Art. 364 Incendio',
        'Art. 366 Terrorismo',
        'Art. 367 Financiación del terrorismo',
        'Art. 368 Falsa incriminación',
        'Art. 369 Delincuencia organizada',
        'Art. 369.1 Reclutamiento de niños, niñas y adolescentes con fines delictivos',
        'Art. 370 Asociación ilícita',
        'Suicidio',
        'Muerte Natural',
		'OTRO',
    ],

    // Medidas cautelares + detalle (catálogo simple)
    'medidas_cautelares' => [
        'MEDIDA CAUTELAR PERSONAL', 'MEDIDA CAUTELAR SOBRE BIENES','AISLAMIENTO','NO CALIFICA FRAGRANCIA','NINGUNA','OTRA',
    ],
    'detalles_medidas' => [
               'DETENCIÓN','PRISIÓN PREVENTIVA','PRESENTACIÓN PERIÓDICA','PROHIBICIÓN DE AUSENTARSE DEL PAÍS',
        'DISPOSITIVO DE VIGILANCIA ELECTRÓNICA','ARRESTO DOMICILIARIO','INTERNAMIENTO PREVENTIVO','OTRA',
    ],

    // Vinculación
    'vinculacion' => ['SI','NO'],

    // Situación jurídica
    'situaciones_juridicas' => [
        'INVESTIGACIÓN',
        'EVALUACIÓN Y PREPARATORIA DE JUICIO',
        'ETAPA DE JUICIO',
        'SOBRESEIMIENTO',
        'SENTENCIA',
        'ARCHIVO',
        'OTRA',
    ],

    // Requerimientos
    'requerimientos' => [
// Nuevos (según tu lista)
    'RECONOCIMIENTO DEL LUGAR',
    'TRASLADO DE EVIDENCIAS/ INDICIOS',
    'VERSIONES DE TESTIGOS Y/O VÍCTIMAS',
    'NOTIFICACIÓN',
    'ENTREGA DE BOLETAS',
    'ENTREVISTAS',
    'SOLICITUD ANTECEDENTES PENALES, POLICIALES Y DIFUSIONES',
    'AVALÚO DE BIENES',
    'ANÁLISIS TELEFÓNICO',
    'ANÁLISIS FINANCIERO',
    'PRESERVACIÓN DE EVIDENCIAS',
    'INGRESO Y ANÁLISIS ELEMENTOS BALÍSTICOS',
    'REGISTRO BIOMÉTRICO',
    'EMISIÓN COPIAS CERTIFICADAS',
    'EMISIÓN DATOS BIOMÉTRICOS',
    'RECONOCIMIENTO DE EVIDENCIAS',

    // Las que ya tenías
    'PERICIA TELEFÓNICA',
    'PERICIA OPERADORAS',
    'PERICIA BALÍSTICA',
    'INFORME CRIMINALÍSTICA',
    'OFICIO FISCALÍA',
    'CADENA DE CUSTODIA',
    'OTRO',
    ],

    // Escenas (si ya usas estas en otro módulo, mantén)
    'escenas' => ['DOMICILIO','VÍA PÚBLICA','COMERCIO','BALDÍO','VEHÍCULO','RÍO/CANAL','ÁREA RURAL','OTRA'],
];
